---
- hosts: windows
  gather_facts: no
  tasks:
    - ansible.windows.win_feature:
       name: AD-Domain-Services
       state: present
       include_management_tools: true
    - ansible.windows.win_domain:
        dns_domain_name: costumers.com
        safe_mode_password: P@ssw0rd
      register: domain_install
    - ansible.windows.win_reboot:
      when: domain_install.reboot_required