---
- name: copy files
  become: true
  hosts: all
  
  tasks:
    - name: execute copy file
      copy:
        src: /data/file1
        dest: /data/file2
        owner: root
        group: root
        mode: '0644'

